name: Golang Tests
run-name: Testing golang code 🚀
on: [push, pull_request]
jobs:
  golang-testing:
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - run: go test ./... -cover
